export const seedData = {
  profile: {
    fullName: "Abdulrhman Ashraf",
    logoText: "AS",
    headline: "Senior Backend Software Engineer",
    summary:
      "Senior Backend Software Engineer with 3+ years of experience architecting and scaling enterprise-grade backend systems, including within regulated banking environments. Proven track record owning backend infrastructure simultaneously across web and mobile product squads, with deep expertise in RESTful and GraphQL API design, secure microservices architecture, and database optimization. Recognized as a trusted cross-functional partner to Integration, Information Security, DevOps, and Network Security teams, consistently resolving complex technical blockers, remediating vulnerabilities, and driving new features from design through production.",
    about:
      "Senior Backend Software Engineer based in Cairo, Egypt. Currently owning enterprise microservices at Arab African International Bank across website and mobile product squads. Previously built geospatial, supply-chain, and ERP backends at Mahaseel, Techs Experts, and Orange Digital Center. Bachelor's in Business Information Systems, Helwan University, Very Good (81.6%).",
    location: "Cairo, Egypt",
    email: "abdulrahmanashraf9898@gmail.com",
    phone: "+201284400082",
    cvUrl: "/cv/Abdulrhman_Ashraf_Senior_Backend_Software_Engineer_CV.pdf",
    imageUrl: "/images/Profile.webp",
    imageLazyUrl: "/images/ProfileLazy.webp",
  },
  experiences: [
    {
      jobTitle: "Senior Backend Software Engineer",
      company: "Arab African International Bank (AAIB)",
      dateRange: "Aug 2025 – Present",
      sortOrder: 0,
      focus:
        "Enterprise Microservices Architecture · RESTful & GraphQL APIs · Cross-Platform Backend Ownership (Web & Mobile) · Database Optimization · Security Vulnerability Remediation · Cross-Functional Collaboration",
      bullets: [
        "Own and maintain enterprise-grade backend microservices spanning both website and mobile product squads in parallel, ensuring consistent business logic and API contracts across platforms.",
        "Design and develop RESTful and GraphQL APIs in strict adherence to banking-grade security and regulatory compliance standards.",
        "Lead the resolution of complex, cross-service technical blockers, partnering directly with Information Security to identify, prioritize, and remediate vulnerabilities ahead of release.",
        "Drive database design and query optimization initiatives to improve reliability and response times for high-traffic, real-time services.",
        "Perform code reviews and uphold clean architecture and coding standards to safeguard long-term maintainability across squads.",
        "Lead cross-functional coordination across Integration, DevOps, Information Security, and Network Security teams to ensure secure, seamless deployment of new features.",
        "Deliver new backend features end-to-end — from design through production rollout — balancing strict security requirements with delivery timelines.",
      ],
    },
    {
      jobTitle: "Mid-Level Backend Software Engineer",
      company: "Mahaseel",
      dateRange: "Aug 2024 – Aug 2025",
      sortOrder: 1,
      bullets: [
        "Designed and implemented scalable PostgreSQL and MongoDB schemas and ERDs supporting multiple production platforms.",
        "Developed and maintained backend systems using NestJS, Node.js, and Express.js.",
        "Optimized system performance through query tuning and consistent enforcement of backend best practices.",
        "Collaborated closely with frontend and mobile teams to support API integration and feature delivery.",
        "Diagnosed and resolved frontend integration issues, ensuring seamless cross-platform functionality.",
        "Contributed to code reviews, pair programming, and unit/integration testing.",
      ],
    },
    {
      jobTitle: "Back-End Engineer",
      company: "Techs Experts",
      dateRange: "Sep 2023 – Aug 2024",
      sortOrder: 2,
      bullets: [
        "Designed and implemented relational database schemas and ERDs.",
        "Developed backend logic and business rules using Laravel, PHP, and MySQL.",
        "Built and documented RESTful APIs and web services for multiple client products.",
        "Created reusable Laravel components to support clean, efficient front-end integration.",
      ],
    },
    {
      jobTitle: "Back-End Engineer",
      company: "Orange Digital Center",
      dateRange: "Oct 2022 – Aug 2023",
      sortOrder: 3,
      bullets: [
        "Developed and maintained high-performance backend systems for internal platforms.",
        "Designed and implemented RESTful APIs to support new product features.",
        "Focused on backend optimization, debugging, and performance improvements.",
      ],
    },
  ],
  educations: [
    {
      degree: "Bachelor's Degree in Business Information Systems",
      school: "Helwan University",
      dateRange: "2016 – 2020",
      sortOrder: 0,
      details: ["Grade: Very Good (81.6%)"],
    },
  ],
  skills: [
    { name: "JavaScript", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 0 },
    { name: "TypeScript", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 1 },
    { name: "Java", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 2 },
    { name: "PHP", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 3 },
    { name: "C++", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 4 },
    { name: "C", group: "Languages", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 5 },
    { name: "NestJS", group: "Frameworks", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 6 },
    { name: "Express.js", group: "Frameworks", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 7 },
    { name: "Laravel", group: "Frameworks", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 8 },
    { name: "Spring Boot (familiar)", group: "Frameworks", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 9 },
    { name: "PostgreSQL", group: "Databases", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 10 },
    { name: "MongoDB", group: "Databases", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 11 },
    { name: "MySQL", group: "Databases", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 12 },
    { name: "REST APIs", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 13 },
    { name: "GraphQL", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 14 },
    { name: "Microservices", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 15 },
    { name: "Kafka", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 16 },
    { name: "RabbitMQ", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 17 },
    { name: "Docker", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 18 },
    { name: "Git", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 19 },
    { name: "Swagger", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 20 },
    { name: "Prisma", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 21 },
    { name: "TypeORM", group: "Tools & Concepts", iconUrl: "", shadowColor: "", shadowColorHover: "", sortOrder: 22 },
  ],
  socialLinks: [
    { name: "github", url: "https://github.com/AbdulrahmanAshraf98" },
    { name: "linkedin", url: "https://www.linkedin.com/in/abdulrahmanashraf98/" },
    { name: "x", url: "" },
    { name: "gmail", url: "mailto:abdulrahmanashraf9898@gmail.com" },
  ],
  contacts: [
    { title: "Email", info: "abdulrahmanashraf9898@gmail.com" },
    { title: "Phone", info: "+201284400082" },
    { title: "Location", info: "Cairo, Egypt" },
  ],
  projects: [
    {
      name: "Mazraaty Digital Agriculture Platform (B2G UAE)",
      slug: "mazraaty",
      featured: true,
      published: true,
      company: "Mahaseel",
      description:
        "Enterprise-scale geospatial backend for UAE government stakeholders. Implemented PostGIS spatial analysis and reporting dashboards, secure authentication, and real-time data processing for a B2G agriculture platform at Mahaseel.",
      bullets: [
        "Built enterprise-scale geospatial backend systems for government stakeholders.",
        "Implemented PostGIS-based spatial analysis and reporting dashboards.",
        "Integrated secure authentication and real-time data processing.",
      ],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["NestJS", "TypeScript", "PostgreSQL", "PostGIS", "TypeORM", "Redis", "Azure APIs", "UAE Pass"],
      categories: ["Key projects"],
    },
    {
      name: "EFB System — Supply Chain & Traceability Platform",
      slug: "efb-system",
      featured: true,
      published: true,
      company: "Mahaseel",
      description:
        "End-to-end supply chain traceability for the Egyptian Food Bank. QR-code tracking, multi-warehouse inventory, procurement-to-delivery with automated purchase orders and quality control, stock validation, fulfillment, and waste workflows for government agencies, associations, and beneficiaries.",
      bullets: [
        "Developed an end-to-end supply chain traceability system with QR-code-based tracking for real-time monitoring.",
        "Built a robust backend architecture for multi-warehouse inventory management and distribution workflows.",
        "Designed a comprehensive procurement-to-delivery pipeline with automated purchase order and quality control systems.",
        "Automated stock validation, order fulfillment, and waste management processes.",
        "Implemented a multi-stakeholder platform supporting government agencies, associations, and beneficiaries.",
      ],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["NestJS", "TypeScript", "MongoDB", "Cloud Storage", "Redis"],
      categories: ["Key projects"],
    },
    {
      name: "Mahaseel — Agricultural Services Platform",
      slug: "mahaseel",
      featured: true,
      published: true,
      company: "Mahaseel",
      description:
        "Community Wall, Service Requests, and Agri Waste Marketplace. Resolved backend bottlenecks, added dynamic RBAC, internationalization, and Google/Facebook OAuth social login.",
      bullets: [
        "Built Community Wall, Service Requests, and Agri Waste Marketplace modules.",
        "Enhanced performance by resolving backend bottlenecks and optimizing queries.",
        "Improved ACL with dynamic role-based permissions and security policies.",
        "Integrated internationalization and social login (Google/Facebook OAuth).",
      ],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["TypeScript", "NestJS", "MongoDB", "Redis", "Swagger", "Azure"],
      categories: ["Key projects"],
    },
    {
      name: "New Gini — ERP System",
      slug: "new-gini",
      featured: true,
      published: true,
      company: "Techs Experts",
      description:
        "Mobile ERP APIs for ride-hailing, delivery, car rental, and chat, with dynamic permission systems. Built at Techs Experts on Laravel and MySQL.",
      bullets: [
        "Developed APIs for mobile ERP modules (ride-hailing, delivery, car rental, chat).",
        "Implemented dynamic permission systems.",
      ],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Firebase"],
      categories: ["Key projects"],
    },
    {
      name: "Elmarsah — E-Commerce Platform",
      slug: "elmarsah",
      featured: true,
      published: true,
      company: "Techs Experts",
      description:
        "Complete e-commerce system with dashboards, order management, and payments. Built at Techs Experts.",
      bullets: ["Built a complete e-commerce system with dashboards, order management, and payments."],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "Firebase"],
      categories: ["Key projects"],
    },
    {
      name: "Orange Digital Center Dashboard",
      slug: "odc-dashboard",
      featured: true,
      published: true,
      company: "Orange Digital Center",
      description:
        "Backend and frontend for a real-time interactive internal dashboard at Orange Digital Center.",
      bullets: ["Developed backend and frontend for a real-time interactive dashboard."],
      imageUrl: "",
      lazyImageUrl: "",
      liveUrl: "",
      githubUrl: "",
      videoUrl: "",
      technologies: ["NestJS", "TypeScript", "React", "Redux Toolkit", "Docker", "Swagger"],
      categories: ["Key projects"],
    },
    {
      name: "Movie App",
      slug: "movie-app",
      featured: false,
      published: true,
      description: "Movie discovery app powered by TMDB.",
      imageUrl: "/projects/Movie-App.webp",
      lazyImageUrl: "/projects/Movie-AppLazy.webp",
      liveUrl: "https://movie-app-six-xi.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/movie-app",
      videoUrl: "https://www.youtube.com/watch?v=kjDcGwcrmCQ",
      technologies: ["React JS", "Firebase", "TMDB API", "Redux"],
      categories: ["Earlier work"],
    },
    {
      name: "Personal Portfolio",
      slug: "personal-portfolio",
      featured: false,
      published: true,
      description: "Original PWA portfolio, now this microservices platform.",
      imageUrl: "/projects/Portfolio.webp",
      lazyImageUrl: "/projects/PortfolioLazy.webp",
      liveUrl: "https://portfolio-mauve-gamma-79.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/Portfolio",
      videoUrl: "",
      technologies: ["React JS", "Tailwind CSS", "PWA"],
      categories: ["Earlier work"],
    },
    {
      name: "Youtube-Clone",
      slug: "youtube-clone",
      featured: false,
      published: true,
      description: "YouTube clone with Material UI and YouTube API.",
      imageUrl: "/projects/YoutubeClone.webp",
      lazyImageUrl: "/projects/YoutubeCloneLazy.webp",
      liveUrl: "https://youtube-clone-react-mu.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/Youtube-Clone-React-MU",
      videoUrl: "",
      technologies: ["React JS", "Material UI", "YouTube API"],
      categories: ["Earlier work"],
    },
    {
      name: "Crow Cloths E-Commerce",
      slug: "crown-clothes",
      featured: false,
      published: true,
      description: "E-commerce store with Firebase auth and Stripe checkout.",
      imageUrl: "/projects/Crow-Clothes.webp",
      lazyImageUrl: "/projects/Crow-ClothesLazy.webp",
      liveUrl: "https://crown-clothes.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/Crown-Clothes",
      videoUrl: "",
      technologies: ["React JS", "Firebase", "Stripe"],
      categories: ["Earlier work"],
    },
    {
      name: "E-Commerce Js",
      slug: "e-commerce-js",
      featured: false,
      published: true,
      description: "Vanilla JavaScript e-commerce with Tailwind and Webpack.",
      imageUrl: "/projects/JsE-CommerceApp.webp",
      lazyImageUrl: "/projects/JsE-CommerceAppLazy.webp",
      liveUrl: "https://e-commerce-vanlia-javascript.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/e-commerce-Vanlia-Javascript-Tailwind-Css-Wepback",
      videoUrl: "",
      technologies: ["JavaScript", "Tailwind CSS"],
      categories: ["Earlier work"],
    },
    {
      name: "Forkify Recipe Website",
      slug: "forkify",
      featured: false,
      published: true,
      description: "Recipe search app with public food APIs.",
      imageUrl: "/projects/forkify.webp",
      lazyImageUrl: "/projects/forkifyLazy.webp",
      liveUrl: "https://forkify-project-two.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/forkifyProject",
      videoUrl: "",
      technologies: ["JavaScript", "Sass"],
      categories: ["Earlier work"],
    },
    {
      name: "Mapty",
      slug: "mapty",
      featured: false,
      published: true,
      description: "Workout mapper using geolocation APIs.",
      imageUrl: "/projects/mapty.webp",
      lazyImageUrl: "/projects/maptyLazy.webp",
      liveUrl: "https://mapty-app-seven.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/MaptyApp",
      videoUrl: "",
      technologies: ["JavaScript"],
      categories: ["Earlier work"],
    },
    {
      name: "Idemy",
      slug: "idemy",
      featured: false,
      published: true,
      description: "Education landing template.",
      imageUrl: "/projects/idemy.webp",
      lazyImageUrl: "/projects/idemyLazy.webp",
      liveUrl: "https://i-demy-template.vercel.app/index.html",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/iDemy-Template",
      videoUrl: "",
      technologies: ["HTML", "CSS", "Bootstrap"],
      categories: ["Earlier work"],
    },
    {
      name: "Planteo",
      slug: "planteo",
      featured: false,
      published: true,
      description: "Plant shop HTML template.",
      imageUrl: "/projects/planteo.webp",
      lazyImageUrl: "/projects/planteoLazy.webp",
      liveUrl: "https://abdulrahmanashraf98.github.io/planteo-template/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/planteo-template",
      videoUrl: "",
      technologies: ["HTML", "CSS", "Bootstrap"],
      categories: ["Earlier work"],
    },
    {
      name: "Bruno Simmons",
      slug: "bruno-simmons",
      featured: false,
      published: true,
      description: "Figma-to-HTML conversion.",
      imageUrl: "/projects/BrunoSimmons.webp",
      lazyImageUrl: "/projects/BrunoSimmonsLazy.webp",
      liveUrl: "https://html-css-java-script.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/convert-Figma-to-html-and-css-",
      videoUrl: "",
      technologies: ["HTML", "CSS"],
      categories: ["Earlier work"],
    },
    {
      name: "TimeZone",
      slug: "timezone",
      featured: false,
      published: true,
      description: "Watch store HTML/CSS template.",
      imageUrl: "/projects/timezone.webp",
      lazyImageUrl: "/projects/timezoneLazy.webp",
      liveUrl: "https://template-four.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/template-four",
      videoUrl: "",
      technologies: ["HTML", "CSS"],
      categories: ["Earlier work"],
    },
    {
      name: "Anime",
      slug: "anime",
      featured: false,
      published: true,
      description: "Anime landing template.",
      imageUrl: "/projects/Anime.webp",
      lazyImageUrl: "/projects/AnimeLazy.webp",
      liveUrl: "https://template-6.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/template-6",
      videoUrl: "",
      technologies: ["HTML", "CSS"],
      categories: ["Earlier work"],
    },
    {
      name: "Bakery",
      slug: "bakery",
      featured: false,
      published: true,
      description: "Bakery landing template.",
      imageUrl: "/projects/Bakery.webp",
      lazyImageUrl: "/projects/BakeryLazy.webp",
      liveUrl: "https://template-three-chi.vercel.app/",
      githubUrl: "https://github.com/AbdulrahmanAshraf98/template-three",
      videoUrl: "",
      technologies: ["HTML", "CSS"],
      categories: ["Earlier work"],
    },
  ],
  settings: {
    signatureText: "AS",
    linkedinUrl: "https://www.linkedin.com/in/abdulrahmanashraf98/",
    xUrl: "",
    sectionOrder: ["skills", "experience", "projects", "education", "featured", "certificates", "earlier"],
  },
  highlights: [],
};
